// Auth Context - Auto-generated by Backend Service
// Uses REST API for authentication (WebContainer compatible)
// The Supabase SDK auth methods don't work reliably in WebContainer

import React, { createContext, useContext, useState, useEffect } from 'react';

const AuthContext = createContext(null);

export function AuthProvider({ children }) {
  const [user, setUser] = useState(null);
  const [session, setSession] = useState(null);
  const [loading, setLoading] = useState(true);

  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

  useEffect(() => {
    async function initSession() {
      try {
        // Check for auth callback: Supabase redirects with #access_token=... after email confirmation
        const hash = window.location.hash;
        if (hash && hash.includes('access_token=')) {
          const params = new URLSearchParams(hash.substring(1));
          const accessToken = params.get('access_token');
          const refreshToken = params.get('refresh_token');

          if (accessToken) {
            // Fetch user data with the token
            const userRes = await fetch(`${supabaseUrl}/auth/v1/user`, {
              headers: {
                'Authorization': `Bearer ${accessToken}`,
                'apikey': supabaseAnonKey,
              },
            });

            if (userRes.ok) {
              const userData = await userRes.json();
              const sessionData = {
                access_token: accessToken,
                refresh_token: refreshToken,
                user: userData,
              };
              localStorage.setItem('supabase_session', JSON.stringify(sessionData));
              setSession(sessionData);
              setUser(userData);
              // Clean hash from URL
              window.history.replaceState(null, '', window.location.pathname + window.location.search);
              setLoading(false);
              return;
            }
          }
        }

        // Fall through: check for existing session in localStorage
        const savedSession = localStorage.getItem('supabase_session');
        if (savedSession) {
          try {
            const parsed = JSON.parse(savedSession);
            setSession(parsed);
            setUser(parsed.user);
          } catch (e) {
            localStorage.removeItem('supabase_session');
          }
        }
      } catch (e) {
        console.error('Auth init error:', e);
      }
      setLoading(false);
    }
    initSession();
  }, []);

  const signUp = async (email, password, metadata = {}) => {
    // Pass redirect_to so Supabase confirmation email redirects back to this app
    const redirectTo = import.meta.env.VITE_AUTH_REDIRECT_URL || (window.location.origin + window.location.pathname);
    const response = await fetch(`${supabaseUrl}/auth/v1/signup?redirect_to=${encodeURIComponent(redirectTo)}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': supabaseAnonKey,
      },
      body: JSON.stringify({ email, password, data: metadata }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error_description || data.msg || 'Signup failed');
    }

    if (data.access_token) {
      // User was auto-confirmed (e.g., email confirmation disabled)
      const sessionData = {
        access_token: data.access_token,
        refresh_token: data.refresh_token,
        user: data.user,
      };
      localStorage.setItem('supabase_session', JSON.stringify(sessionData));
      setSession(sessionData);
      setUser(data.user);
    }

    return data;
  };

  const signIn = async (email, password) => {
    const response = await fetch(`${supabaseUrl}/auth/v1/token?grant_type=password`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': supabaseAnonKey,
      },
      body: JSON.stringify({ email, password }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error_description || data.msg || 'Login failed');
    }

    const sessionData = {
      access_token: data.access_token,
      refresh_token: data.refresh_token,
      user: data.user,
    };
    localStorage.setItem('supabase_session', JSON.stringify(sessionData));
    setSession(sessionData);
    setUser(data.user);

    return data;
  };

  const signOut = async () => {
    localStorage.removeItem('supabase_session');
    setSession(null);
    setUser(null);
  };

  return (
    <AuthContext.Provider value={{ user, session, loading, signUp, signIn, signOut }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}
