// Supabase Client - Auto-generated by Backend Service
// DO NOT import supabase directly for authenticated operations
// Use the useSupabase() hook instead to ensure proper authentication

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Base client - for public/unauthenticated queries only
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Factory for authenticated client - used by useSupabase() hook
export function createAuthenticatedClient(accessToken) {
  const client = createClient(supabaseUrl, supabaseAnonKey, {
    global: {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    },
  });

  // Authenticate the realtime WebSocket connection for RLS to work
  client.realtime.setAuth(accessToken);

  return client;
}
