// useSupabase Hook - Auto-generated by Backend Service
// ALWAYS use this hook for Supabase operations to ensure proper authentication
// This hook automatically uses an authenticated client when the user is logged in

import { useMemo } from 'react';
import { useAuth } from './auth-context';
import { supabase, createAuthenticatedClient } from './supabase';

export function useSupabase() {
  const { session, user } = useAuth();

  const client = useMemo(() => {
    if (session?.access_token) {
      // User is logged in - return authenticated client
      return createAuthenticatedClient(session.access_token);
    }
    // Not logged in - return base client (for public queries only)
    return supabase;
  }, [session?.access_token]);

  return {
    supabase: client,
    isAuthenticated: !!session,
    user,
  };
}
